services:
  - type: web
    name: userReg-backend
    env: java
    plan: free
    buildCommand: "mvn clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    rootDir: UserReg/backend
    envVars:
      - key: JAVA_VERSION
        value: 17
