sudo delete web service userreg-backendservices:
  - type: web
    name: userreg-backend
    env: java
    rootDir: UserReg/backend
   buildCommand: "mvn clean package -DskipTests"
    startCommand: "java -jar target/UserReg-0.0.1-SNAPSHOT.jar"
    plan: free
